name: flutter_env_mode_updater
description: A Flutter desktop app + CLI tool to toggle pubspec dependencies.
publish_to: "none"

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  yaml: ^3.1.0
  path: any
  yaml_writer: any
  file_picker: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
